"""Add soft delete to products and articles

Revision ID: 15b46c47e6b6
Revises: da2710e61b54
Create Date: 2026-01-16 22:54:19.809716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b46c47e6b6'
down_revision = 'da2710e61b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###
    op.execute("UPDATE articles SET is_deleted = 0 WHERE is_deleted IS NULL")
    op.execute("UPDATE products SET is_deleted = 0 WHERE is_deleted IS NULL")

    with op.batch_alter_table('articles') as batch_op:
        batch_op.alter_column('is_deleted', server_default=None)

    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('is_deleted', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###

