"""Replace product_images with product_media

Revision ID: da2710e61b54
Revises: 946ddccae431
Create Date: 2026-01-16 16:40:28.379369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2710e61b54'
down_revision = '946ddccae431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # copy existing images into media table
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, product_id, image_url FROM product_images")).fetchall()
    for r in rows:
        conn.execute(
            sa.text("INSERT INTO product_media (product_id, media_type, url, sort_order) VALUES (:pid, 'image', :url, 0)"),
            {"pid": r.product_id, "url": r.image_url},
        )
    op.drop_table("product_images")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("id"),
        )
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT product_id, url FROM product_media WHERE media_type='image'")).fetchall()
    for r in rows:
        conn.execute(
            sa.text("INSERT INTO product_images (product_id, image_url) VALUES (:pid, :url)"),
            {"pid": r.product_id, "url": r.url},
        )
    op.drop_table("product_media")

    # ### end Alembic commands ###
